### ISSUE TITLE
teach the tool about std APIs

### ISSUE THREAD

**Issue by mvdan** [kortschak/gospel#12]
For example, I'm getting warned about `ValueOf` in the following godoc line:

> such as those used as arguments to reflect.TypeOf or reflect.ValueOf.

**Comment by mvdan** [comment]
Interestingly, it does not care about TypeOf. Link:

https://github.com/burrowers/garble/blob/4c3b90c051a0d24c43ce8f8a2aac4e28fcec4512/main.go#L1150

**Comment by mvdan** [comment]
Another one; it doesn't like `FileInfoToDirEntry` in:

> CouldBeScript is a shortcut for CouldBeScript2(fs.FileInfoToDirEntry(info)).

**Comment by kortschak** [comment]
You aren't seeing TypeOf because it's used in the module, if you want to see those, run `gospel -ignore-idents=false`. I don't know where FileInfoToDirEntry, so I can't confirm that one.

**Comment by mvdan** [comment]
> I don't know where FileInfoToDirEntry, so I can't confirm that one.

It's from https://pkg.go.dev/io/fs#FileInfoToDirEntry.

> because it's used in the module

I see. I would hope that all exported identifiers from transitive dependencies would be added to the dictionary automatically, then I wouldn't have these false positives :)

**Comment by kortschak** [comment]
That could be added, I've not looked into walking the AST from dependencies, this should just be a matter of AST walking on the `Imports` map's packages, no?
