### ISSUE TITLE
add more common Go-isms to the known words set

### ISSUE THREAD

**Issue by mvdan** [kortschak/gospel#14]
Adding a few here as I've come across them. Some are rather generic to programming, others are somewhat specific to Go.

* builtins
* errored
* recurse
* config
* filesystem
* unexport
* codepoints
* tokenize
* lexing
* lexed
* backquote
* ascii
* unescaped
* unsetting
* html
* mutex
* vendored
* env (as in `go env`)
* funcs (as in plural of the `func` keyword)
* hacky
* uncomment
* v4 (as in major version, could be any vN)
* charset
* lossy
* hasher
* KiB (and MiB, etc?)

I realise I can add these to my local dictionary per-project, but I also assume you want to capture the common ones in the tool.

It's very likely that I'm not spelling some of these right, for example by omitting a dash like `un-setting`. Happy to be told to spell better :) But in those cases, it would be nice to be told what the right spelling is, because I don't.

**Comment by mvdan** [comment]
A few more words, from a second pass:

* www
* namespace
* framepointer
* whitespaces
* gofmt
* nolint

I think it would also be good to ignore all sequences like `go:foobar` and `go-foobar`; I'm getting matches for e.g. `go-sumtype`.

**Comment by kortschak** [comment]
Which repos are you finding words marked in? I'm adding heuristics so that I don't have to add so many special words to the known words list. Mainly I'm look at words that are found in the go source tree, but that has a particular flavour of word.

**Comment by mvdan** [comment]
I've mainly been testing on https://github.com/mvdan/sh and https://github.com/burrowers/garble so far.

**Comment by kortschak** [comment]
Fixed with #39.

**Comment by kortschak** [comment]
The units (kiB, MiB etc) issue was confounding the camel splitter because it also splits on camel case (surprisingly). I have added specific unit handling.
