### ISSUE TITLE
teach the tool about flag arguments

### ISSUE THREAD

**Issue by mvdan** [kortschak/gospel#16]
For example, the following flag names are being marked as typos:

> Obtained from "go list -deps runtime"

> If the assembler is running just for -gensymabis,

> If we recognize an argument, we're not running within -toolexec.

Presumably, if we see a word that begins with a dash, we could assume it's a flag name and ignore it.

**Comment by kortschak** [comment]
By the time the spell check is looking at words, there is no dash. However, I have been considering keeping a reference to the context for heuristics like this.
