### ISSUE TITLE
feature: support per-repo or per-module (or per-workspace) dictionaries

### ISSUE THREAD

**Issue by philpennock** [kortschak/gospel#3]
Rather than each developer working on a code-base having to teach their local install about project-specific terminology, it would be great if gospel could support project-specific dictionaries without needing to set DICTIONARIES env-vars dynamically.

This could be per-repository, walking up until it finds the VCS root; I've found `golang.org/x/tools/go/vcs` to be useful and it has `FromDir()` which should help.

This could be per-module.

This could support "sibling to workspace".

Given a search path, all of the above would be neat.

**Comment by kortschak** [comment]
It's not guaranteed that a module will be in a repo, but for gospel to work at all, the code must be part of a module, so a two step search, for for a repo root (may fail) and then for a module root (can't fail), adding any directories that it finds (on top of the LANG based dictionary specified on the command line) would work well. I think a `.words` file sounds like a reasonably sane name.

To extend this, be able to write out a dictionary of misspelled words for human vetting would make creating of the words file easier.

**Comment by kortschak** [comment]
I have an implementation for this in #4 if you'd like to take a look. I think it's probably enough, but it would be good to get others' input.

**Comment by kortschak** [comment]
Closed by #4.
