### ISSUE TITLE
improve docs for hunspell

### ISSUE THREAD

**Issue by mvdan** [kortschak/gospel#38]
- [x] Document `gospel -misspellings .words ./...` as a way to kickstart a project dictionary, removing the words which are actual misspellings
- [x] Document where to learn more about hunspell, e.g. `man 5 hunspell` and where to find defined affixes for en_US, such as `/usr/share/hunspell/en_US.aff`
- [x] Give some examples of lines one can add to a `.words` file, such as `builtin/S` for a plural, an example for a verb, an adjective, etc
- [x] Document that the starting number in a dict file is a hint, and may be replaced with a dummy value like `1` (you said this somewhere and I forget where)

**Comment by kortschak** [comment]
The word "builtin" is already in the en_US dictionary and this impacts on how "builting/S" is handled (it looks like it is ignored). From what I understand after my crash course in this area, first rule added wins.

**Comment by mvdan** [comment]
Hmm. Do I need to then add `builtins`? In bash lingo, "builtin" is a noun with a plural, as far as I understand.

**Comment by kortschak** [comment]
Unfortunately, yes. Until there is a better back end that can be used in hunspell's place. And you're right, the plural should be valid.

**Comment by mvdan** [comment]
Ah, sounds good. Perhaps another tidbit to add to the docs: you can't use affixes for words which are already in the base dictionary.
