### ISSUE TITLE
make gospel usable in ci

### ISSUE THREAD

**Issue by kortschak** [kortschak/gospel#8]
Currently gospel is likely to generate too much noise to be usable in a CI context but this should be fixable with relatively few additions.

- [x] provide a config file to run from
- [x] have a non-zero exit status when misspellings are found ~(optionally?)~
- [x] allow common apparent misspelling classes to be ignored — this is already done with all upper-case words. for example:
    - [x] floating point expressions
    - [x] hexadecimal numbers (with or without 0x prefix)
    - [x] non-decimal number prefixed numbers
    - [x] x, u and U prefixed rune literals
    - [x] check whether underscore_separated_words that have been identified as misspellings are constructed from correctly spelled words
    - [x] regular-expression based ignoring of words, for example for `/^rfc[0-9]+$/i`
    - [x] very long words to help ignore base64 and other troublesome encodings
    - [x] entropy-based filtering of strings
- [x] ignore words found in valid, vet-passing struct tags
- [x] ~~a linter directive to ignore files in the form `//lint:file-ignore spelling reason` paralleling the [staticcheck approach](https://staticcheck.io/docs/configuration/#file-based-linter-directives). A finer-grained approach could also be used like statichceck's [line-based approach](https://staticcheck.io/docs/configuration/#line-based-linter-directives), but based on blocks rather than lines.~~

**Comment by mvdan** [comment]
I'd like to gently push back on lint directives, given that we already have a "words" file. I'd much prefer using that to ignore false positives.

**Comment by kortschak** [comment]
Noted. I have been rethinking that (and am not in a hurry to add it), though there are still reasons to include it; try running gospel on the go source tree, particularly in time/tzdata — I'm not convinced that a there are sane heuristics that cover that kind of data well. What I was thinking for an alternative was `//line:spelling add [<word> <word> <word>  ... ]` and collecting these to add to `knownWords where they can include affix rules.

**Comment by kortschak** [comment]
Tasks completed. Will revisit as needed.
