### ISSUE TITLE
another bag of domain-specific words to teach gospel about

### ISSUE THREAD

**Issue by mvdan** [kortschak/gospel#83]
* metacharacter
* automata
* IPv6
* subnet
* backtick
* utf-8
* testdata (from the standard directory name supported by Go)
* ldflags (from Go's flag; same with gcflags and others probably)

**Comment by kortschak** [comment]
ldflags should already be masked by the command flag mask rule and utf-8 is arguably incorrect (should be UTF-8 which will already be ignored with ignore-upper).

**Comment by mvdan** [comment]
Below are some false positives that seem to contradict what you've said :)

```
$ git rev-parse HEAD
058efb4651578128ff27d8b3339fc367ea7adb1e
$ pacman -Qs hunspell
local/hunspell 1.7.0-3
    Spell checker and morphological analyzer library and program
local/hunspell-en_us 2020.12.07-4
    US English hunspell dictionaries
```

```
cmd/cue/cmd/version.go:40:5: "ldflags" is misspelled in comment
    // version be set by a builder using
    // -ldflags='-X cuelang.org/go/cmd/cue/cmd.version=<version>'.
    // However, people should prefer building via a mechanism which

pkg/regexp/manual.go:30:22: "automata" is misspelled in comment
    //  https://swtch.com/~rsc/regexp/regexp1.html
    // or any book about automata theory.
    //

pkg/net/ip.go:145:72: "subnet" is misspelled in comment
    // IPCIDR reports whether ip is a valid IPv4 or IPv6 address with CIDR subnet notation.
    //
```

Your point about `utf-8` is fair enough, though.

**Comment by kortschak** [comment]
That's odd. How I check is running hunspell directly for the words that I claimed are in the dictionary. I'll take a look tomorrow.

The flags one is behind a flag (-mask-flags) because I don't think the heuristic is reliable enough. This is probably a good reason to include those in the words list.
