### ISSUE TITLE
add a "version" flag

### ISSUE THREAD

**Issue by mvdan** [kortschak/gospel#86]
I was trying to report a bug and realised that fetching the gospel version I'm running is not particularly easy. These days, with VCS build stamping, it should be easy to report the version.

If you want, you can copy this code of mine from another project (minus the test mocking env vars):

https://github.com/burrowers/garble/blob/master/main.go#L327-L368

For a development build, it ends up like:

```
$ garble version
mvdan.cc/garble (devel) 

Build settings:
       -compiler gc
     CGO_ENABLED 1
          GOARCH amd64
            GOOS linux
         GOAMD64 v3
             vcs git
    vcs.revision 6a39ad2d8157bfa0a93d121cbf6bdf437815ca43
        vcs.time 2022-03-26T09:34:51Z
    vcs.modified false
```

A release build would look pretty similar - the build settings are always printed - but the version would be a useful tag rather than "devel".

**Comment by kortschak** [comment]
I always just use `go version -m =binary`, but I can certainly add this.
